---
- name: Ensure podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure the gin service group exists
  ansible.builtin.group:
    name: ginservice
    state: present
  register: ginservice_group

- name: Ensure gin user exists
  ansible.builtin.user:
    name: ginuser
    group: ginservice
    password_lock: true
  register: ginuser_user

- name: Create XDG user dir for gin user
  ansible.builtin.file:
    path: /run/user/{{ ginuser_user.uid }}
    state: directory
    owner: ginuser
    mode: o=rwx,g=,o=

- name: ginuser | Check if lingering is enabled
  ansible.builtin.stat: 
    path: /var/lib/systemd/linger/ginuser
  register: linger

- name: ginuser | Enable lingering
  ansible.builtin.command: loginctl enable-linger ginuser
  when: 
    - not linger.stat.exists
    - systemd_config.enable_linger | default('yes')

- name: Set cap_setuid=ep on /usr/bin/newuidmap
  community.general.capabilities:
    path: /usr/bin/newuidmap
    capability: cap_setuid=ep
    state: present

- name: Set cap_setuid=ep on /usr/bin/newgidmap
  community.general.capabilities:
    path: /usr/bin/newgidmap
    capability: cap_setgid=ep
    state: present
