---
- name: Ensure gin service directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
    owner: ginuser
    group: ginservice
  loop:
    - /srv/gin
    - /srv/gin/config
    - /srv/gin/config/postgres
    - /srv/gin/volumes
    - /srv/gin/volumes/ginweb
    - /srv/gin/gindata
    - /srv/gin/gindata/gin-postgresdb

- name: Ensure postgres secrets file exists
  ansible.builtin.template:
    dest: /srv/gin/config/postgres/pgressecrets.env
    src: pgressecrets.env
    owner: ginuser
    group: ginservice
    mode: '0660'

- name: Check if gin config exists
  ansible.builtin.stat:
    path: /srv/gin/volumes/ginweb/gogs/conf/app.ini
  register: gin_config_stat

- name: Ensure gin config has proper rights if it exists
  ansible.builtin.file:
    path: /srv/gin/volumes/ginweb/gogs/conf/app.ini
    mode: '0664'
    owner: ginuser
    group: ginservice
  when: gin_config_stat.stat.exists
